### ISSUE TITLE
Is bind example okay?

### ISSUE THREAD

**Issue by xgvargas** [Moeriki/shifting#2]
I'm trying to undertand you binding example code, but I feel kind of lost... the `shifting` module is not even used on it. Should it be used in place of `say`?

```javascript
var myAPI = {
  hello: 'Bonjour',
  sayHello: function (name, callback) {
    callback(null, this.hello + ' ' + name + '!');
  }
}

say.call([myAPI, myAPI.sayHello], 'World')
  .then(console.log); // logs 'Bonjour World!'
```
Any way, great module, thanks!

**Comment by moeriki** [comment]
Good catch! `say` should indeed be `shifting`. I'll update.
